# Copyright © 2022-2025, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
# -----------------------------------------------------------
# Control Plane Initialization — Primary Node
# -----------------------------------------------------------

- name: Copy cluster config (kubeadm-config.yaml)
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/kubernetes/{{ item }}.yaml"
    mode: "0600"
  with_items:
    - kubeadm-config
  tags:
    - install
    - update

# Workaround for https://github.com/kube-vip/kube-vip/issues/684
# to use super-admin.conf during kubeadm init (fixed in future kube-vip releases)
- name: Update kube-vip.yaml to use super-admin.conf for kubeadm init in 1.29+
  ansible.builtin.replace:
    path: /etc/kubernetes/manifests/kube-vip.yaml
    regexp: "path: /etc/kubernetes/admin.conf"
    replace: "path: /etc/kubernetes/super-admin.conf"
  when: kubernetes_version is version("1.29.0", "ge", version_type="semver")
  tags:
    - install
    - update

# Initialize Kubernetes Control Plane
- name: Run kubeadm init
  ansible.builtin.command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml --upload-certs
  register: kubeadm_init
  changed_when: "'initialized successfully' in kubeadm_init.stdout or 'This node has joined the cluster' in kubeadm_init.stdout"
  tags:
    - install

# Workaround revert — restore original kube-vip.yaml
- name: Restore kube-vip.yaml to use admin.conf for kubeadm init in 1.29+
  ansible.builtin.replace:
    path: /etc/kubernetes/manifests/kube-vip.yaml
    regexp: "path: /etc/kubernetes/super-admin.conf"
    replace: "path: /etc/kubernetes/admin.conf"
  when: kubernetes_version is version("1.29.0", "ge", version_type="semver")
  tags:
    - install
    - update

# Create .kube directory for root
- name: Setup kubernetes .kube directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0755"
  tags:
    - install

# Configure environment for root
- name: Configure env for root
  ansible.builtin.lineinfile:
    path: $HOME/.bashrc
    line: export KUBECONFIG=/etc/kubernetes/admin.conf
  tags:
    - install

# Copy admin.conf to ~/.kube/config for root user
- name: Copy admin.conf file
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    owner: root
    group: root
    mode: "0600"
    remote_src: true
  tags:
    - install

# Fetch kubeconfig locally for later usage
- name: Fetch k8s config
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ inventory_dir }}/{{ kubernetes_cluster_name }}-kubeconfig.conf"
    flat: true
  tags:
    - install
