# Copyright © 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
## sig-storage-local-static-provisioner
kubernetes_LOCAL_VOLUME_NAME: sig-storage-local-static-provisioner-sas
kubernetes_LOCAL_VOLUME_NAMESPACE: kube-system
kubernetes_LOCAL_VOLUME_CHART_NAME: Chart.yaml
kubernetes_LOCAL_VOLUME_REPO: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner.git
kubernetes_LOCAL_VOLUME_CHART_VERSION: 2.8.0
kubernetes_LOCAL_VOLUME_REPO_VERSION: "v{{ kubernetes_LOCAL_VOLUME_CHART_VERSION }}"
kubernetes_LOCAL_VOLUME_REPO_LOCATION: "/tmp/{{ kubernetes_LOCAL_VOLUME_NAME }}"
kubernetes_LOCAL_VOLUME_CONFIG:
  common:
    serviceAccount:
      create: true
  classes:
    - name: local-storage
      hostDir: /mnt/sas/volumes
      volumeMode: Filesystem
      fsType: xfs
      namePattern: "*"
      blockCleanerCommand:
        - "/scripts/quick_reset.sh"
      storageClass: true
  daemonset:
    tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: cas
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: singlestore
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
                - key: workload.sas.com/class
                  operator: In
                  values:
                    - stateful
                    - stateless
                    - cas
                    - singlestore
              matchFields: []
            weight: 100
          - preference:
              matchExpressions:
                - key: workload.sas.com/class
                  operator: NotIn
                  values:
                    - compute
              matchFields: []
            weight: 50
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.azure.com/mode
                  operator: NotIn
                  values:
                    - system
              matchFields: []
