# Copyright © 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
#
# TODO: Add user variables to the calico manifest to
#       adjust items needed when working on bare metal
#       vm type systems.
#
- name: Install Operator
  ansible.builtin.shell: |
    kubectl create -f "https://raw.githubusercontent.com/projectcalico/calico/v{{ kubernetes_cni_version }}/manifests/operator-crds.yaml" && \
    kubectl create -f "https://raw.githubusercontent.com/projectcalico/calico/v{{ kubernetes_cni_version }}/manifests/tigera-operator.yaml"
  tags:
    - install
    - update

# Wait for Tigera CRDs to be available
# - name: Wait for Tigera CRDs to be registered
#   ansible.builtin.shell: |
#     until kubectl get crds | grep installations.operator.tigera.io; do sleep 5; done
#   retries: 12
#   delay: 5
#   register: crd_check
#   until: crd_check.rc == 0
#  tags:
#    - install
#    - update

- name: Create custom-resources for our cluster
  ansible.builtin.template:
    src: "templates/{{ item }}.tmpl"
    dest: "/tmp/{{ item }}.yaml"
  with_items:
    - custom-resources
  tags:
    - install
    - update

- name: Apply custom-resources
  ansible.builtin.shell: |
    kubectl create -f /tmp/custom-resources.yaml
  tags:
    - install
    - update
